# This file was generated by GoReleaser. DO NOT EDIT.
class CommitColors < Formula
  desc "See a lovely color swatch in your terminal every time you author a commit."
  homepage "https://github.com/sparkbox/commit-colors"
  version "2.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sparkbox/commit-colors/releases/download/2.0.0/commit-colors_2.0.0_Darwin_x86_64.tar.gz"
    sha256 "aa7b81188c07a669b620bb7a8876151183fdfb013c9b1b5aa5ec9212041cd2f4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sparkbox/commit-colors/releases/download/2.0.0/commit-colors_2.0.0_Linux_x86_64.tar.gz"
      sha256 "503a9d8d458db2f9e564aa5183eea5e655757b6663b84acbf7ff29813b0f224e"
    end
  end

  def install
    bin.install "commit-colors"
  end
end
