# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CommitColors < Formula
  desc "See a lovely color swatch in your terminal every time you author a commit."
  homepage "https://github.com/sparkbox/commit-colors"
  version "2.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sparkbox/commit-colors/releases/download/2.0.1/commit-colors_2.0.1_Darwin_x86_64.tar.gz"
      sha256 "0441304d3349582927c2a01069365dd35b7341a0cfb2de714636d5b45dbf8a25"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sparkbox/commit-colors/releases/download/2.0.1/commit-colors_2.0.1_Linux_x86_64.tar.gz"
      sha256 "959c62894f35a419e30cdfb94bf624c102e6743827c70f5c7017247d25efbe9e"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sparkbox/commit-colors/releases/download/2.0.1/commit-colors_2.0.1_Linux_arm64.tar.gz"
      sha256 "04ba9d91d3097662839435909e5e2c95e355beb8b8fd8ee6f74561b1996da9ba"
    end
  end

  def install
    bin.install "commit-colors"
  end
end
